# Generated by Django 3.0.2 on 2020-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myocr',
            name='Flag',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myocr',
            name='image',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
