# Generated by Django 3.0.2 on 2020-01-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200116_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myocr',
            name='Flag',
        ),
    ]
